### ISSUE TITLE
Support bearer token based authentication 

### ISSUE THREAD

**Issue by dilawar** [shadowylab/ntfy#5]
It looks like only username/password-based authentication is currently supported. NTFY supports bearer token-based auth as well (https://docs.ntfy.sh/publish/#access-tokens). If it is already implemented, it's not easy to locate in documents.

**Comment by yukibtc** [comment]
Just released `v0.6` which include support for authentication with access token.

**Comment by dilawar** [comment]
Thanks. This was fast! 🥳
