### ISSUE TITLE
Use derive-builder instead of manually implementing builder pattern.

### ISSUE THREAD

**Issue by dessalines** [shadowylab/ntfy#6]
I took a quick look through the code here, and you could use https://github.com/colin-kiegel/rust-derive-builder .

I actually stopped doing this in my codebases and use [derive-new](https://github.com/nrc/derive-new), but it's up to you.

**Comment by yukibtc** [comment]
> I took a quick look through the code here, and you could use https://github.com/colin-kiegel/rust-derive-builder .
> 
> I actually stopped doing this in my codebases and use [derive-new](https://github.com/nrc/derive-new), but it's up to you.

Thanks for suggestion. I prefer to use only the strictly required deps in my projects (at exception of `thiserror` which I've used somewhere), for this reason I'm not using it :)
